# Generated by Django 2.0.4 on 2019-03-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsTbl',
            fields=[
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('title_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('description_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('address_en', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contacts_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountriesTbl',
            fields=[
                ('country_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('country_status', models.IntegerField()),
                ('country_blacklist', models.IntegerField()),
                ('country_order', models.IntegerField(blank=True, null=True)),
                ('country_name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'countries_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultContactsTbl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('title_en', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('description_en', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('address_en', models.CharField(blank=True, max_length=45, null=True)),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'default_contacts_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionsResponseTable',
            fields=[
                ('response', models.CharField(max_length=100)),
                ('response_feedback', models.CharField(max_length=2000)),
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('opt_response', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'feedback_questions_response_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionsTable',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=2000)),
                ('question_option', models.CharField(max_length=2000)),
                ('question_title_en', models.CharField(max_length=2000)),
                ('question_option_en', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'feedback_questions_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManpowersTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower_name', models.CharField(max_length=455)),
            ],
            options={
                'db_table': 'manpowers_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MigrantTbl',
            fields=[
                ('migrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('migrant_name', models.CharField(max_length=200)),
                ('migrant_phone', models.CharField(max_length=100)),
                ('migrant_sex', models.CharField(max_length=100)),
                ('migrant_age', models.IntegerField()),
                ('fb_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('current_country', models.CharField(blank=True, max_length=200, null=True)),
                ('inactive_date', models.CharField(blank=True, max_length=45, null=True)),
                ('migrant_img', models.TextField(blank=True, null=True)),
                ('migrant_tblcol', models.CharField(blank=True, max_length=45, null=True)),
                ('percent_comp', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migrant_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionsTbl',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=200)),
                ('option_text_en', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'options_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionsTbl',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_step', models.CharField(max_length=500)),
                ('question_description', models.TextField()),
                ('question_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('response_type', models.IntegerField()),
                ('question_title', models.CharField(max_length=500)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('variable', models.CharField(blank=True, max_length=200, null=True)),
                ('conflict_description', models.CharField(max_length=2000)),
                ('question_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('question_step_en', models.CharField(max_length=500)),
                ('question_description_en', models.TextField()),
                ('conflict_description_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('question_call', models.CharField(blank=True, max_length=45, null=True)),
                ('question_video', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'questions_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TilesTbl',
            fields=[
                ('tile_id', models.AutoField(primary_key=True, serialize=False)),
                ('tile_title', models.CharField(max_length=100)),
                ('tile_type', models.CharField(max_length=100)),
                ('tile_description', models.CharField(max_length=500)),
                ('tile_order', models.IntegerField()),
                ('tile_title_en', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tiles_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=100, unique=True)),
                ('user_sex', models.CharField(max_length=100)),
                ('fb_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_age', models.IntegerField()),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user_img', models.TextField(blank=True, null=True)),
                ('percent_comp', models.FloatField(blank=True, null=True)),
                ('current_country', models.CharField(blank=True, max_length=45, null=True)),
                ('last_active', models.CharField(blank=True, max_length=45, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseTbl',
            fields=[
                ('migrant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apis.MigrantTbl')),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('response_variable', models.CharField(blank=True, max_length=50, null=True)),
                ('is_error', models.CharField(blank=True, max_length=50, null=True)),
                ('tile_id', models.IntegerField(blank=True, null=True)),
                ('question_query', models.CharField(blank=True, max_length=2000, null=True)),
                ('response_time', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'response_tbl',
                'managed': False,
            },
        ),
    ]
