# Generated by Django 2.0.4 on 2019-03-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactstbl',
            options={},
        ),
    ]
